import React, { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import BG from "../Component/BG";
import searchImg from "../assets/search.svg";
import Footer from "../Component/Footer";

const faqData = [
  {
    question: "Do I need a YouTube channel to use this website?",
    answer:
      "No, a YouTube channel isn't required. This website focuses on processing public YouTube videos, not your own channel content. It retrieves captions, transcribes audio, and summarizes the information. You can use it to understand existing videos on YouTube.",
  },
  {
    question:
      "Can I retrieve captions for any YouTube video using ScribeLight?",
    answer:
      "Maybe. ScribeLight will try, but some videos might not have captions uploaded by the creator.",
  },
  {
    question: "What happens if a YouTube video doesn't have captions?",
    answer:
      "No worries! If captions aren't available, ScribeLight can use Whisper AI to transcribe the audio for you.",
  },
  {
    question: "How accurate are the summaries generated by this website?",
    answer:
      "ScribeLight strives for accuracy by utilizing advanced AI models, but Summarization is complex. There's always a chance of nuance being missed.",
  },
  {
    question: "Is there a mobile app available for ScribeLight?",
    answer:
      "ScribeLight is a web-based application! This means you can access it using the web browser on your phone or tablet.",
  },
];

const FAQItem = ({ question, answer, isOpen, onClick }) => {
    return (
    <div className="relative z-10 border border-neutral-700 rounded-2xl overflow-hidden mb-4">
      <button
        className="w-full flex justify-between items-center p-4 text-left focus:outline-none bg-zinc-900 border-t-gray-500/50 border-l-gray-500/50 border-b-gray-800/10 border-r-gray-800/10 border"
        onClick={onClick}
      >
        <span className="font-medium text-white">{question}</span>
        {isOpen ? (
          <ChevronUp className="h-5 w-5" color="#ffffff" />
        ) : (
          <ChevronDown className="h-5 w-5" color="#ffffff" />
        )}
      </button>
      <div
        className={`overflow-hidden transition-all transition duration-700  ${
          isOpen ? "max-h-96" : "max-h-0"
        }`}
      >
        <div className="p-4 bg-zinc-900 text-sm text-white/50 font-normal">
          <p>{answer}</p>
        </div>
      </div>
    </div>
  );
};

const FAQPage = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [openItems, setOpenItems] = useState({});

  const toggleItem = (index) => {
    setOpenItems((prevState) => ({
      ...prevState,
      [index]: !prevState[index],
    }));
  };

  const filteredFAQ = faqData.filter(
    (item) =>
      item.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.answer.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="bg-neutral-900 min-h-screen relative">
      {/* Background component with proper positioning */}
      <BG className="fixed inset-0 w-full h-full -z-10" />

      <div className="min-h-screen p-4 md:p-8 lg:p-12 relative z-10">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold text-center mb-8 text-white pt-10 font-space-grotesk">
            Frequently Asked Questions
          </h1>

          <div className="relative mb-8">
            <input
              type="text"
              placeholder="Search FAQ..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full mx-auto p-3 pl-4 rounded-2xl focus:outline-none bg-neutral-800 text-white border-t-gray-500/50 border-l-gray-500/50 border-b-gray-800/50 border-r-gray-800/50 border shadow-[inset_2px_2px_2px_rgba(0,0,0,0.3)]"
            />
          </div>

          <div>
            {filteredFAQ.map((item, index) => (
              <FAQItem
                key={index}
                question={item.question}
                answer={item.answer}
                isOpen={openItems[index]}
                onClick={() => toggleItem(index)}
              />
            ))}
          </div>

          {filteredFAQ.length === 0 && (
            <div>
              <p className="text-center font-thin text-white mt-8">
                Oops! . . . Seems you have other questions beyond our FAQ!
                <img src={searchImg} className="mx-auto mt-4" alt="Search" />
              </p>
            </div>
          )}
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default FAQPage;
