import React, { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import BG from "../Component/BG";
import searchImg from "../assets/search.svg";
import Footer from "../Component/Footer";

const faqData = [
  {
    question: "Do I need a YouTube channel to use this website?",
    answer:
      "No, a YouTube channel isn't required. This website focuses on processing public YouTube videos, not your own channel content. It retrieves captions, transcribes audio, and summarizes the information. You can use it to understand existing videos on YouTube.",
  },
  {
    question:
      "Can I retrieve captions for any YouTube video using ScribeLight?",
    answer:
      "Maybe. ScribeLight will try, but some videos might not have captions uploaded by the creator.",
  },
  {
    question: "What happens if a YouTube video doesn't have captions?",
    answer:
      "No worries! If captions aren't available, ScribeLight can use Whisper AI to transcribe the audio for you.",
  },
  {
    question: "How accurate are the summaries generated by this website?",
    answer:
      "ScribeLight strives for accuracy by utilizing advanced AI models, but Summarization is complex. There's always a chance of nuance being missed.",
  },
  {
    question: "Is there a mobile app available for ScribeLight?",
    answer:
      "ScribeLight is a web-based application! This means you can access it using the web browser on your phone or tablet.",
  },
];

const FAQItem = ({ question, answer, isOpen, onClick }) => {
  return (
    <div className="relative z-10 border rounded-lg overflow-hidden mb-4">
      <button
        className="w-full flex justify-between items-center p-4 text-left focus:outline-none bg-zinc-900"
        onClick={onClick}
      >
        <span className="font-medium text-white">{question}</span>
        {isOpen ? (
          <ChevronUp className="h-5 w-5" color="#ffffff" />
        ) : (
          <ChevronDown className="h-5 w-5" color="#ffffff" />
        )}
      </button>
      <div
        className={`overflow-hidden transition-all duration-500 ease-in-out ${
          isOpen ? "max-h-96" : "max-h-0"
        }`}
      >
        <div className="p-4 bg-gradient-to-r text-sm from-[#f13a3a5f] to-[#470000] text-gray-200 font-light">
          <p>{answer}</p>
        </div>
      </div>
    </div>
  );
};

const FAQPage = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [openItems, setOpenItems] = useState({});

  const toggleItem = (index) => {
    setOpenItems((prevState) => ({
      ...prevState,
      [index]: !prevState[index],
    }));
  };

  const filteredFAQ = faqData.filter(
    (item) =>
      item.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.answer.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="relative z-10">
      {/* Add the background component here */}
      <BG className="absolute top-0 left-0 w-full h-full -z-10 pointer-events-none" />

      <div className="min-h-screen p-4 md:p-8 lg:p-12 relative z-10">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold text-center mb-8 text-white pt-10">
            Frequently Asked Questions
          </h1>

          <input
            type="text"
            placeholder="Search FAQ..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full mx-auto p-2 mb-8 border rounded-md focus:outline-none focus:ring-2 focus:ring-red-300"
          />

          <div>
            {filteredFAQ.map((item, index) => (
              <FAQItem
                key={index}
                question={item.question}
                answer={item.answer}
                isOpen={openItems[index]}
                onClick={() => toggleItem(index)}
              />
            ))}
          </div>

          {filteredFAQ.length === 0 && (
            <div>
              <p className="text-center font-thin text-white mt-8">
                Oops! . . . Seems you have other questions beyond our FAQ!
                <img src={searchImg} className="mx-auto" alt="Search" />
              </p>
            </div>
          )}
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default FAQPage;
